//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/AlohaService")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserInfo", Namespace="http://schemas.datacontract.org/2004/07/AlohaService.ServiceDataContracts")]
    [System.SerializableAttribute()]
    public partial class UserInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FullNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordSaltField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RegistrationStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SequrityAnswerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SequrityQuestionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserRoleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FullName {
            get {
                return this.FullNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FullNameField, value) != true)) {
                    this.FullNameField = value;
                    this.RaisePropertyChanged("FullName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PasswordSalt {
            get {
                return this.PasswordSaltField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordSaltField, value) != true)) {
                    this.PasswordSaltField = value;
                    this.RaisePropertyChanged("PasswordSalt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RegistrationStatus {
            get {
                return this.RegistrationStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.RegistrationStatusField, value) != true)) {
                    this.RegistrationStatusField = value;
                    this.RaisePropertyChanged("RegistrationStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SequrityAnswer {
            get {
                return this.SequrityAnswerField;
            }
            set {
                if ((object.ReferenceEquals(this.SequrityAnswerField, value) != true)) {
                    this.SequrityAnswerField = value;
                    this.RaisePropertyChanged("SequrityAnswer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SequrityQuestion {
            get {
                return this.SequrityQuestionField;
            }
            set {
                if ((object.ReferenceEquals(this.SequrityQuestionField, value) != true)) {
                    this.SequrityQuestionField = value;
                    this.RaisePropertyChanged("SequrityQuestion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserRole {
            get {
                return this.UserRoleField;
            }
            set {
                if ((this.UserRoleField.Equals(value) != true)) {
                    this.UserRoleField = value;
                    this.RaisePropertyChanged("UserRole");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OperationResult", Namespace="http://schemas.datacontract.org/2004/07/AlohaService.ServiceDataContracts")]
    [System.SerializableAttribute()]
    public partial class OperationResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long CreatedObjectIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SuccessField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long CreatedObjectId {
            get {
                return this.CreatedObjectIdField;
            }
            set {
                if ((this.CreatedObjectIdField.Equals(value) != true)) {
                    this.CreatedObjectIdField = value;
                    this.RaisePropertyChanged("CreatedObjectId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success {
            get {
                return this.SuccessField;
            }
            set {
                if ((this.SuccessField.Equals(value) != true)) {
                    this.SuccessField = value;
                    this.RaisePropertyChanged("Success");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OperationResultValueOfUserdi1iiSGT", Namespace="http://schemas.datacontract.org/2004/07/AlohaService.ServiceDataContracts")]
    [System.SerializableAttribute()]
    public partial class OperationResultValueOfUserdi1iiSGT : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WindowsFormsApp1.ServiceReference1.User ResultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SuccessField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WindowsFormsApp1.ServiceReference1.User Result {
            get {
                return this.ResultField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultField, value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success {
            get {
                return this.SuccessField;
            }
            set {
                if ((this.SuccessField.Equals(value) != true)) {
                    this.SuccessField = value;
                    this.RaisePropertyChanged("Success");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/AlohaService.ServiceDataContracts")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FullNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordSaltField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RegistrationStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SequrityAnswerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SequrityQuestionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserRoleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FullName {
            get {
                return this.FullNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FullNameField, value) != true)) {
                    this.FullNameField = value;
                    this.RaisePropertyChanged("FullName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PasswordSalt {
            get {
                return this.PasswordSaltField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordSaltField, value) != true)) {
                    this.PasswordSaltField = value;
                    this.RaisePropertyChanged("PasswordSalt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RegistrationStatus {
            get {
                return this.RegistrationStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.RegistrationStatusField, value) != true)) {
                    this.RegistrationStatusField = value;
                    this.RaisePropertyChanged("RegistrationStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SequrityAnswer {
            get {
                return this.SequrityAnswerField;
            }
            set {
                if ((object.ReferenceEquals(this.SequrityAnswerField, value) != true)) {
                    this.SequrityAnswerField = value;
                    this.RaisePropertyChanged("SequrityAnswer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SequrityQuestion {
            get {
                return this.SequrityQuestionField;
            }
            set {
                if ((object.ReferenceEquals(this.SequrityQuestionField, value) != true)) {
                    this.SequrityQuestionField = value;
                    this.RaisePropertyChanged("SequrityQuestion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserRole {
            get {
                return this.UserRoleField;
            }
            set {
                if ((this.UserRoleField.Equals(value) != true)) {
                    this.UserRoleField = value;
                    this.RaisePropertyChanged("UserRole");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AirCompanyInfo", Namespace="http://schemas.datacontract.org/2004/07/AlohaService.ServiceDataContracts")]
    [System.SerializableAttribute()]
    public partial class AirCompanyInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DefaultPaymentTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DiscountTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DefaultPaymentType {
            get {
                return this.DefaultPaymentTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.DefaultPaymentTypeField, value) != true)) {
                    this.DefaultPaymentTypeField = value;
                    this.RaisePropertyChanged("DefaultPaymentType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DiscountType {
            get {
                return this.DiscountTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.DiscountTypeField, value) != true)) {
                    this.DiscountTypeField = value;
                    this.RaisePropertyChanged("DiscountType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsActive {
            get {
                return this.IsActiveField;
            }
            set {
                if ((this.IsActiveField.Equals(value) != true)) {
                    this.IsActiveField = value;
                    this.RaisePropertyChanged("IsActive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OperationResultValueOfAirCompanydi1iiSGT", Namespace="http://schemas.datacontract.org/2004/07/AlohaService.ServiceDataContracts")]
    [System.SerializableAttribute()]
    public partial class OperationResultValueOfAirCompanydi1iiSGT : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WindowsFormsApp1.ServiceReference1.AirCompany ResultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SuccessField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WindowsFormsApp1.ServiceReference1.AirCompany Result {
            get {
                return this.ResultField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultField, value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success {
            get {
                return this.SuccessField;
            }
            set {
                if ((this.SuccessField.Equals(value) != true)) {
                    this.SuccessField = value;
                    this.RaisePropertyChanged("Success");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AirCompany", Namespace="http://schemas.datacontract.org/2004/07/AlohaService.ServiceDataContracts")]
    [System.SerializableAttribute()]
    public partial class AirCompany : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DefaultPaymentTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DiscountTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DefaultPaymentType {
            get {
                return this.DefaultPaymentTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.DefaultPaymentTypeField, value) != true)) {
                    this.DefaultPaymentTypeField = value;
                    this.RaisePropertyChanged("DefaultPaymentType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DiscountType {
            get {
                return this.DiscountTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.DiscountTypeField, value) != true)) {
                    this.DiscountTypeField = value;
                    this.RaisePropertyChanged("DiscountType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsActive {
            get {
                return this.IsActiveField;
            }
            set {
                if ((this.IsActiveField.Equals(value) != true)) {
                    this.IsActiveField = value;
                    this.RaisePropertyChanged("IsActive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OperationResultValueOfArrayOfAirCompanydi1iiSGT", Namespace="http://schemas.datacontract.org/2004/07/AlohaService.ServiceDataContracts")]
    [System.SerializableAttribute()]
    public partial class OperationResultValueOfArrayOfAirCompanydi1iiSGT : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WindowsFormsApp1.ServiceReference1.AirCompany[] ResultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SuccessField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WindowsFormsApp1.ServiceReference1.AirCompany[] Result {
            get {
                return this.ResultField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultField, value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success {
            get {
                return this.SuccessField;
            }
            set {
                if ((this.SuccessField.Equals(value) != true)) {
                    this.SuccessField = value;
                    this.RaisePropertyChanged("Success");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IAlohaService")]
    public interface IAlohaService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlohaService/GetData", ReplyAction="http://tempuri.org/IAlohaService/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlohaService/GetData", ReplyAction="http://tempuri.org/IAlohaService/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlohaService/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IAlohaService/GetDataUsingDataContractResponse")]
        WindowsFormsApp1.ServiceReference1.CompositeType GetDataUsingDataContract(WindowsFormsApp1.ServiceReference1.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlohaService/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IAlohaService/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.CompositeType> GetDataUsingDataContractAsync(WindowsFormsApp1.ServiceReference1.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlohaService/CreateUser", ReplyAction="http://tempuri.org/IAlohaService/CreateUserResponse")]
        WindowsFormsApp1.ServiceReference1.OperationResult CreateUser(WindowsFormsApp1.ServiceReference1.UserInfo userInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlohaService/CreateUser", ReplyAction="http://tempuri.org/IAlohaService/CreateUserResponse")]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.OperationResult> CreateUserAsync(WindowsFormsApp1.ServiceReference1.UserInfo userInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlohaService/GetUser", ReplyAction="http://tempuri.org/IAlohaService/GetUserResponse")]
        WindowsFormsApp1.ServiceReference1.OperationResultValueOfUserdi1iiSGT GetUser(long userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlohaService/GetUser", ReplyAction="http://tempuri.org/IAlohaService/GetUserResponse")]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.OperationResultValueOfUserdi1iiSGT> GetUserAsync(long userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlohaService/UpdateUser", ReplyAction="http://tempuri.org/IAlohaService/UpdateUserResponse")]
        WindowsFormsApp1.ServiceReference1.OperationResult UpdateUser(long userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlohaService/UpdateUser", ReplyAction="http://tempuri.org/IAlohaService/UpdateUserResponse")]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.OperationResult> UpdateUserAsync(long userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlohaService/DeleteUser", ReplyAction="http://tempuri.org/IAlohaService/DeleteUserResponse")]
        WindowsFormsApp1.ServiceReference1.OperationResult DeleteUser(long userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlohaService/DeleteUser", ReplyAction="http://tempuri.org/IAlohaService/DeleteUserResponse")]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.OperationResult> DeleteUserAsync(long userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlohaService/CreateAirCompany", ReplyAction="http://tempuri.org/IAlohaService/CreateAirCompanyResponse")]
        WindowsFormsApp1.ServiceReference1.OperationResult CreateAirCompany(WindowsFormsApp1.ServiceReference1.AirCompanyInfo airCompany);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlohaService/CreateAirCompany", ReplyAction="http://tempuri.org/IAlohaService/CreateAirCompanyResponse")]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.OperationResult> CreateAirCompanyAsync(WindowsFormsApp1.ServiceReference1.AirCompanyInfo airCompany);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlohaService/GetAirCompany", ReplyAction="http://tempuri.org/IAlohaService/GetAirCompanyResponse")]
        WindowsFormsApp1.ServiceReference1.OperationResultValueOfAirCompanydi1iiSGT GetAirCompany(long airCompanyId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlohaService/GetAirCompany", ReplyAction="http://tempuri.org/IAlohaService/GetAirCompanyResponse")]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.OperationResultValueOfAirCompanydi1iiSGT> GetAirCompanyAsync(long airCompanyId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlohaService/UpdateAirCompany", ReplyAction="http://tempuri.org/IAlohaService/UpdateAirCompanyResponse")]
        WindowsFormsApp1.ServiceReference1.OperationResult UpdateAirCompany(WindowsFormsApp1.ServiceReference1.AirCompany airCompany);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlohaService/UpdateAirCompany", ReplyAction="http://tempuri.org/IAlohaService/UpdateAirCompanyResponse")]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.OperationResult> UpdateAirCompanyAsync(WindowsFormsApp1.ServiceReference1.AirCompany airCompany);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlohaService/DeleteAirCompany", ReplyAction="http://tempuri.org/IAlohaService/DeleteAirCompanyResponse")]
        WindowsFormsApp1.ServiceReference1.OperationResult DeleteAirCompany(long airCompanyId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlohaService/DeleteAirCompany", ReplyAction="http://tempuri.org/IAlohaService/DeleteAirCompanyResponse")]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.OperationResult> DeleteAirCompanyAsync(long airCompanyId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlohaService/GetAirCompanyList", ReplyAction="http://tempuri.org/IAlohaService/GetAirCompanyListResponse")]
        WindowsFormsApp1.ServiceReference1.OperationResultValueOfArrayOfAirCompanydi1iiSGT GetAirCompanyList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlohaService/GetAirCompanyList", ReplyAction="http://tempuri.org/IAlohaService/GetAirCompanyListResponse")]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.OperationResultValueOfArrayOfAirCompanydi1iiSGT> GetAirCompanyListAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAlohaServiceChannel : WindowsFormsApp1.ServiceReference1.IAlohaService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AlohaServiceClient : System.ServiceModel.ClientBase<WindowsFormsApp1.ServiceReference1.IAlohaService>, WindowsFormsApp1.ServiceReference1.IAlohaService {
        
        public AlohaServiceClient() {
        }
        
        public AlohaServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AlohaServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AlohaServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AlohaServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public WindowsFormsApp1.ServiceReference1.CompositeType GetDataUsingDataContract(WindowsFormsApp1.ServiceReference1.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.CompositeType> GetDataUsingDataContractAsync(WindowsFormsApp1.ServiceReference1.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
        
        public WindowsFormsApp1.ServiceReference1.OperationResult CreateUser(WindowsFormsApp1.ServiceReference1.UserInfo userInfo) {
            return base.Channel.CreateUser(userInfo);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.OperationResult> CreateUserAsync(WindowsFormsApp1.ServiceReference1.UserInfo userInfo) {
            return base.Channel.CreateUserAsync(userInfo);
        }
        
        public WindowsFormsApp1.ServiceReference1.OperationResultValueOfUserdi1iiSGT GetUser(long userId) {
            return base.Channel.GetUser(userId);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.OperationResultValueOfUserdi1iiSGT> GetUserAsync(long userId) {
            return base.Channel.GetUserAsync(userId);
        }
        
        public WindowsFormsApp1.ServiceReference1.OperationResult UpdateUser(long userId) {
            return base.Channel.UpdateUser(userId);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.OperationResult> UpdateUserAsync(long userId) {
            return base.Channel.UpdateUserAsync(userId);
        }
        
        public WindowsFormsApp1.ServiceReference1.OperationResult DeleteUser(long userId) {
            return base.Channel.DeleteUser(userId);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.OperationResult> DeleteUserAsync(long userId) {
            return base.Channel.DeleteUserAsync(userId);
        }
        
        public WindowsFormsApp1.ServiceReference1.OperationResult CreateAirCompany(WindowsFormsApp1.ServiceReference1.AirCompanyInfo airCompany) {
            return base.Channel.CreateAirCompany(airCompany);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.OperationResult> CreateAirCompanyAsync(WindowsFormsApp1.ServiceReference1.AirCompanyInfo airCompany) {
            return base.Channel.CreateAirCompanyAsync(airCompany);
        }
        
        public WindowsFormsApp1.ServiceReference1.OperationResultValueOfAirCompanydi1iiSGT GetAirCompany(long airCompanyId) {
            return base.Channel.GetAirCompany(airCompanyId);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.OperationResultValueOfAirCompanydi1iiSGT> GetAirCompanyAsync(long airCompanyId) {
            return base.Channel.GetAirCompanyAsync(airCompanyId);
        }
        
        public WindowsFormsApp1.ServiceReference1.OperationResult UpdateAirCompany(WindowsFormsApp1.ServiceReference1.AirCompany airCompany) {
            return base.Channel.UpdateAirCompany(airCompany);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.OperationResult> UpdateAirCompanyAsync(WindowsFormsApp1.ServiceReference1.AirCompany airCompany) {
            return base.Channel.UpdateAirCompanyAsync(airCompany);
        }
        
        public WindowsFormsApp1.ServiceReference1.OperationResult DeleteAirCompany(long airCompanyId) {
            return base.Channel.DeleteAirCompany(airCompanyId);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.OperationResult> DeleteAirCompanyAsync(long airCompanyId) {
            return base.Channel.DeleteAirCompanyAsync(airCompanyId);
        }
        
        public WindowsFormsApp1.ServiceReference1.OperationResultValueOfArrayOfAirCompanydi1iiSGT GetAirCompanyList() {
            return base.Channel.GetAirCompanyList();
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.OperationResultValueOfArrayOfAirCompanydi1iiSGT> GetAirCompanyListAsync() {
            return base.Channel.GetAirCompanyListAsync();
        }
    }
}
